#pragma once

#define APOLLO_MOUSE_BUTTON_1         0
#define APOLLO_MOUSE_BUTTON_2         1
#define APOLLO_MOUSE_BUTTON_3         2
#define APOLLO_MOUSE_BUTTON_4         3
#define APOLLO_MOUSE_BUTTON_5         4
#define APOLLO_MOUSE_BUTTON_6         5
#define APOLLO_MOUSE_BUTTON_7         6
#define APOLLO_MOUSE_BUTTON_8         7
#define APOLLO_MOUSE_BUTTON_LAST      APOLLO_MOUSE_BUTTON_8
#define APOLLO_MOUSE_BUTTON_LEFT      APOLLO_MOUSE_BUTTON_1
#define APOLLO_MOUSE_BUTTON_RIGHT     APOLLO_MOUSE_BUTTON_2
#define APOLLO_MOUSE_BUTTON_MIDDLE    APOLLO_MOUSE_BUTTON_3